apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://containous.github.io/traefik-helm-chart/traefik-6.1.1.tgz
  set:
    additionalArguments:
      - "--metrics.prometheus"
